### ISSUE TITLE
Create 'Federal Application Process'

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/help-center#11]
#Please create a Help Center page titled 'Federal Application Process' 

Not sure if you want it under FAQ or Working in Govt

[Federal Application Process - Extended Content.docx](https://github.com/USAJOBS/help-center/files/196475/Federal.Application.Process.-.Extended.Content.docx)

**Comment by humancompanion** [comment]
Added to the site. Just needs review from @dalenard21 next week.

**Comment by dalenard21** [comment]
This page looks good. It's linked as an FAQ "How does the application process work?"

I think we can close it.
