### ISSUE TITLE
Add content to How to understand search results

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/help-center#20]
This page is still a blank shell. I believe we have content for it. Just need to get it into the site.

**Comment by dalenard21** [comment]
@humancompanion 

waiting for content from Julie.

**Comment by humancompanion** [comment]
I added the content from Julie. I agree with what you wrote the application process, Debbie, that most of this content is elsewhere (advanced, filters, job announcement, etc.). Anyway, the content is in there now for you to edit. I had to add something so that the Contact Us topic selector would return something for this topic.
